server:
  port: 8889
spring:
  datasource:
    url: jdbc:mysql://139.155.247.54:3306/union?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xiangfeng
    password: xiangfeng123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhj.entity

